apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
        timestamp: "{{ .Release.Revision }}"
      name: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Release.Name }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- range $key, $value := .Values.env }}
          {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
        volumeMounts:
          - name: var-log
            mountPath: /var/log
            readOnly: true
          - name: minikube-containers
            mountPath: /mnt/sda1/var/lib/docker/containers
            readOnly: true
          - name: journal-log
            mountPath: /run/log/journal
            readOnly: true
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: minikube-containers
          hostPath:
            path: /mnt/sda1/var/lib/docker/containers
        - name: journal-log
          hostPath:
            path: /run/log/journal
